source 'http://rubygems.org'

group :development do
  gem 'guard'
  gem 'guard-rspec'
  gem 'guard-bundler'
  gem 'rb-fsevent'
end

group :test do
  gem 'rspec'
  gem 'spork'
  gem 'guard-spork'
  gem 'growl'
end
