# https://github.com/guard/guard
# ignore_paths 'foo', 'bar'

group 'eulur-lab' do
  guard 'bundler' do
    watch('Gemfile')
  end
  
  guard 'rspec', :cli => '--color --format doc --drb' do
    watch(%r{^spec/.+_spec\.rb$})
    watch(%r{^lib/(.+)\.rb$})     { |m| "spec/lib/#{m[1]}_spec.rb" }
    watch('spec/spec_helper.rb')  { "spec" }
  end
end

